### ISSUE TITLE
Missing option value -A

### ISSUE THREAD

**Issue by danilobenozzo** [saloot/NeuralNetworkTomography#1]
Hi, I noticed that the function parse_commands_inf_algo in auxiliary_functions_inference.py does not consider the case opt=='-A'. And it assigns the number of recorded samples, i.e. T, both to no_stimul_rounds and file_name_data.
db

**Comment by saloot** [comment]
Hi Danilo
Thanks a lot for your point. That was indeed the case and I deeply thank you for that.
I have fixed the issue.
Thanks again
Best
